services:
  db:
    image: postgis/postgis:15-3.3
    container_name: reliefmind_db
    environment:
      - POSTGRES_USER=relief_user
      - POSTGRES_PASSWORD=relief_pass
      - POSTGRES_DB=reliefmind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
